# Generated by Django 2.2 on 2023-03-27 08:42
from __future__ import annotations

from django.db import models, migrations


class Migration(migrations.Migration):
    dependencies = [
        ("translator", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="evaldata",
            name="target_agent",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
